# Generated by Django 3.2.7 on 2021-11-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0007_residentialproperties_locationframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialproperties',
            name='flowPlan_Image',
            field=models.ImageField(null=True, upload_to='ResidentialInvesment/flowPlan'),
        ),
    ]
