# Generated by Django 3.2.7 on 2021-11-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='uploaded_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
