# Generated by Django 3.2.7 on 2021-11-16 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OFFPlanAndInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('Location', models.CharField(max_length=200)),
                ('LocationFrame', models.TextField(blank=True, null=True)),
                ('Price', models.CharField(max_length=100)),
                ('video_url', models.TextField(null=True)),
                ('Completion_date', models.DateField()),
                ('flowPlan_Image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='OfPlanInvesments/flowPlan')),
                ('Dashboard_Image', models.ImageField(upload_to='OfPlanInvesments/')),
                ('Developer', models.CharField(max_length=200, null=True)),
                ('Development_type', models.TextField(null=True)),
                ('num_bedRooms', models.CharField(max_length=100, null=True)),
                ('num_WashRooms', models.CharField(default='1', max_length=100, null=True)),
                ('num_Garage', models.CharField(default='1', max_length=100, null=True)),
                ('Area', models.CharField(default='1', max_length=100, null=True)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instalment_name', models.CharField(max_length=100, null=True)),
                ('Installment_date', models.CharField(max_length=100, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offsure.offplanandinvestment')),
            ],
        ),
        migrations.CreateModel(
            name='OffPlanGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(null=True, upload_to='OfPlanInvesments/Gallery')),
                ('description', models.TextField(null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offsure.offplanandinvestment')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investmentPlan', models.CharField(blank=True, max_length=100, null=True)),
                ('investmentDetails', models.TextField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offsure.offplanandinvestment')),
            ],
        ),
        migrations.CreateModel(
            name='Amenitie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offsure.offplanandinvestment')),
            ],
        ),
    ]
