# Generated by Django 3.2.7 on 2021-11-27 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offsure', '0003_alter_offplangallery_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offplanandinvestment',
            old_name='LocationFrame',
            new_name='locationFrame',
        ),
    ]
