# Generated by Django 3.2.7 on 2021-10-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0002_rename_imageg_residentialpropertiesimages_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResidentialPropertiesImages',
            new_name='ResidentialPropertiesImage',
        ),
        migrations.AddField(
            model_name='redsidentialproperties',
            name='Dashboard_Image',
            field=models.ImageField(null=True, upload_to='Media/ResidentialInvesment'),
        ),
    ]
