# Generated by Django 3.2.7 on 2021-10-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0003_auto_20211015_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redsidentialproperties',
            name='Dashboard_Image',
            field=models.ImageField(null=True, upload_to='ResidentialInvesment'),
        ),
        migrations.AlterField(
            model_name='residentialpropertiesimage',
            name='Image',
            field=models.ImageField(upload_to='ResidentialInvesment/Gallery'),
        ),
    ]
