# Generated by Django 3.2.7 on 2021-10-29 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0003_alter_residentialproperties_num_garage'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialproperties',
            name='property_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='residentialproperties',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Amenitie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.residentialproperties')),
            ],
        ),
    ]
