# Generated by Django 3.2.7 on 2021-10-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0004_auto_20211029_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialproperties',
            name='video_url',
            field=models.TextField(null=True),
        ),
    ]
