# Generated by Django 3.2.7 on 2021-11-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0005_residentialproperties_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialproperties',
            name='uploaded_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
