# Generated by Django 3.2.7 on 2021-11-12 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0008_residentialproperties_flowplan_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instalment_name', models.CharField(max_length=100, null=True)),
                ('Installment_date', models.CharField(max_length=100, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.residentialproperties')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investmentPlan', models.CharField(blank=True, max_length=100, null=True)),
                ('investmentDetails', models.TextField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.residentialproperties')),
            ],
        ),
    ]
