# Generated by Django 3.2.7 on 2021-11-27 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeDashboardSlider',
        ),
    ]
