# Generated by Django 3.2.7 on 2021-11-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0006_residentialproperties_uploaded_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialproperties',
            name='locationFrame',
            field=models.TextField(blank=True, null=True),
        ),
    ]
