# Generated by Django 3.2.7 on 2021-10-05 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfPlaneInvesments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planeName', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=100)),
                ('complition_date', models.DateField()),
                ('dahboard_images', models.ImageField(upload_to='Media/OfPlanInvesments/')),
            ],
        ),
        migrations.CreateModel(
            name='OffPlanGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Media/OfPlanInvesments/Gallery')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offsure.ofplaneinvesments')),
            ],
        ),
    ]
