# Generated by Django 3.2.7 on 2021-11-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offsure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentplans',
            name='Installment_date',
        ),
        migrations.AddField(
            model_name='paymentplans',
            name='Installment_plan',
            field=models.TextField(null=True),
        ),
    ]
