# Generated by Django 3.2.7 on 2021-10-14 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offsure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofplaneinvesments',
            name='developer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ofplaneinvesments',
            name='development_type',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='payment_plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalment_name', models.CharField(max_length=100, null=True)),
                ('installment_date', models.CharField(max_length=100, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offsure.ofplaneinvesments')),
            ],
        ),
    ]
