# Generated by Django 3.2.7 on 2021-10-15 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offsure', '0002_auto_20211014_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='OFFPlanAndInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlanName', models.CharField(max_length=200)),
                ('Overview', models.TextField()),
                ('Location', models.CharField(max_length=200)),
                ('Price', models.CharField(max_length=100)),
                ('Completion_date', models.DateField()),
                ('Dashboard_Image', models.ImageField(upload_to='Media/OfPlanInvesments/')),
                ('Developer', models.CharField(max_length=200, null=True)),
                ('Development_type', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instalment_name', models.CharField(max_length=100, null=True)),
                ('Installment_date', models.CharField(max_length=100, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offsure.offplanandinvestment')),
            ],
        ),
        migrations.RenameField(
            model_name='offplangallery',
            old_name='image',
            new_name='Image',
        ),
        migrations.DeleteModel(
            name='payment_plans',
        ),
        migrations.AlterField(
            model_name='offplangallery',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offsure.offplanandinvestment'),
        ),
        migrations.DeleteModel(
            name='OfPlaneInvesments',
        ),
    ]
