# Generated by Django 3.2.7 on 2021-10-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offsure', '0003_auto_20211015_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offplanandinvestment',
            name='Dashboard_Image',
            field=models.ImageField(upload_to='OfPlanInvesments/'),
        ),
        migrations.AlterField(
            model_name='offplangallery',
            name='Image',
            field=models.ImageField(upload_to='OfPlanInvesments/Gallery'),
        ),
    ]
