# Generated by Django 3.2.7 on 2021-10-29 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentialProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('Dashboard_Image', models.ImageField(null=True, upload_to='ResidentialInvesment')),
                ('Price', models.CharField(max_length=100)),
                ('Area', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('num_bedRooms', models.CharField(max_length=100)),
                ('num_WashRooms', models.CharField(max_length=100)),
                ('num_Garage', models.CharField(default='1', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='residentialpropertiesimage',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='residentialpropertiesimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.residentialproperties'),
        ),
        migrations.DeleteModel(
            name='RedsidentialProperties',
        ),
    ]
