# Generated by Django 3.2.7 on 2021-10-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0002_auto_20211029_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentialproperties',
            name='num_Garage',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
