# Generated by Django 3.2.7 on 2021-11-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0010_auto_20211118_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentialpropertiesimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
